### ISSUE TITLE
Developer mode not working - getting disabled after restarting the app

### ISSUE THREAD

**Issue by JacekJagosz** [Wunderfitz/harbour-piepmatz#119]
According to readme and your description when you introduced it, developer mode is supposed to give better support of Twitter threads, and I have used it since the beginning.
I don't know with which update it happened, but it doesn't work anymore. When I enable it in settings, put in the Bearer Token, the option gets disabled after I restart the app.
I guess it shows how good your default implementation of threads is that I haven't noticed that dev option stopped working, but this mode only broken for me?
Or maybe now the default mode is the same as dev mode?

**Comment by Wunderfitz** [comment]
Thanks for the report. This must have been broken since the migration to SFOS 4.4. I didn't notice it because I haven't used the dev mode since more than a year - as you said the new implementation for threads works pretty well. I fixed the issue with the dev mode anyway - will be in the next release (however, no ETA yet).
