### ISSUE TITLE
Tweet list in profile page is too small

### ISSUE THREAD

**Issue by d9h02f** [Wunderfitz/harbour-piepmatz#25]
The list of tweets on a profile page is pretty small because the top part, with all the info on that user, doesn't move. It probably makes more sense to move the entire page instead of only the bottom part, because you don't need to see a user's banner or their amount of followers at all times.

**Comment by Wunderfitz** [comment]
The layout of the page will stay for the foreseeable future, but your problem is addressed by the dedicated link to the list of the user's tweets (xxx tweets is underlined) since version 0.3.

**Comment by d9h02f** [comment]
Huh, that wasn't obvious. Even so, there's still a bar at the top which says the name of the user whose tweets you're viewing, but you don't need to know that because every tweet already shows the user's name. That at least seems like a bug (and it goes against Sailfish design principles).

Why do you want to keep the profile page as it is right now? It looks really nice, but I don't see why the information needs to stay on screen all the time (and it also goes against Sailfish design principles). Either the entire profile page should scroll and show tweets, or it shouldn't show tweets at all and redirect the user to a page with only tweets (which is what Tweetian does, I think).

**Comment by Wunderfitz** [comment]
Well, I always want to get the context, so some information what I'm currently looking at. So the header is always visible - no matter if it's pretty obvious what you are looking at (e.g. the tweets of a user) or not (list of followers etc.). That's IMHO a matter of consistency. I consider it a bad habit to let the header scroll with the whole content as the official Jolla apps do it. iOS for instance does this much better and it also was much better in Harmattan. Though, I haven't found this directive somewhere in any documents. Do you have any up-to-date SFOS design guidelines?

And why do I want to keep it that way? Well, just because I like it and at least some others, who I could talk to, like as well. Honestly, I don't know whether the SFOS design principles really go into that detail, but I'm always open for suggestions. And as you mention Tweetian - I wouldn't consider it a reference for beautiful UI design, but that's certainly a matter of taste and there can be endless discussions about  taste, right? ;)
