### ISSUE TITLE
Feature Request: View Threads

### ISSUE THREAD

**Issue by adskankster** [Wunderfitz/harbour-piepmatz#29]
Is it possible to view a thread? Eg select a tweet and see its replies and any it replies to?
It may be possible already, but I've not found out how.

Many thanks.

**Comment by Wunderfitz** [comment]
Unfortunately, this is not (completely) possible. I could only display the tweets the current one is replying to, but not the replies to it as there is no API for that. There are some workarounds, but nothing provides a proper solution. Therefore, I chose not to do anything in this area, but provide a link to the tweet in a browser as Twitter itself shows the results. Just open the context menu of the tweet and select "Open tweet in browser".

**Comment by adskankster** [comment]
Okay, no problem. Thanks though.

**Comment by rodneyrod** [comment]
>There are some workarounds

Could you elaborate on those? I know Twidre does this to some degree of success.

**Comment by Wunderfitz** [comment]
One approach would be to use the search API and look for mentions of the user who is the author of the respective tweet in order to get the replies to the current tweet, but this is very unefficient, error-prone and only works (partially) if the tweet isn't older than 7 days.

The other approach would be to extract the data from the Twitter web page of the respective tweet. However, this might only work if the tweet is public and may violate Twitter's terms and conditions.

**Comment by Thaodan** [comment]
is there no workaround for this?
I mean the official client has this feature

**Comment by Wunderfitz** [comment]
I explained possible workarounds in my previous comment - https://github.com/Wunderfitz/harbour-piepmatz/issues/29#issuecomment-310024456. 

Yes, the official client has this and just to be clear: Piepmatz will _never_ be on a par with the official client. This has several reasons:
- Twitter does not expose all features via their API. Threads are one example, but there are also group DMs, 280-character tweets or polls which currently are not (and probably never will be) accessible via the public API.
- The official Twitter apps use different APIs which are exclusive to the official clients.
- Piepmatz has exactly _one_ developer - that's me and I'm doing this in my spare time. I'm not sure how many developers work on the the official clients (or even popular 3rd party clients on iOS/Android), but I'm sure that they have more than one and that they are paid for it. So unless this doesn't change, I'll only be able to implement the most important features.

I'm open to pull requests, especially for new features (hasn't happened so far at all) in case you want to change that. We can of course also talk about a paid contract, just contact me directly... Just a heads-up: I'm very happy with my current position, so it needs to be pretty good...

**Comment by Thaodan** [comment]
thanks for the explaining it's just threaded  tweets are such an crutial feature when communicating on Twitter .
for once i thought the Twitter api was very open and thought it was usual that third-party clients exist. even on Android their are larger ones.

I now  you do this inyour spare time and the only one working on this .
Maybe there's a way to donate  you for your work ?

**Comment by Wunderfitz** [comment]
Twitter even officially discorages that developers create Twitter App-like 3rd party applications. However, they don't do anything against them and their APIs are relatively open, so that's pretty OK.  But especially for threads, the situation is AFAIK still as I described in June. If you have different information, please let me know.

I don't like donations, but I have concrete plans for a mandatory contribution system (aka paid apps) for SFOS while keeping things open source. It's still in the design phase, so I can't promise anything, but it could be that you'll see something in the near future.
