### ISSUE TITLE
Feature request: add tweet to clipboard 

### ISSUE THREAD

**Issue by Thaodan** [Wunderfitz/harbour-piepmatz#33]
something like this or an option to share  a tweet/search/user .

**Comment by Wunderfitz** [comment]
Putting a tweet's text to the clipboard is slightly different to share a tweet, a search (result) or a user. So could you please elaborate a bit what you are planning to do? IMHO, the most meaningful feature would be to copy the link to the tweet/user to the clipboard, so that a recipient could see the same in the Web client....

**Comment by Wunderfitz** [comment]
Implemented in 9bf3651 - will come with 0.5. :)

**Comment by Thaodan** [comment]
ah thanks didn't even saw that.
I thought of a substitute to a share option.
Is there a way to use the Sailfish share system for that ?

**Comment by Wunderfitz** [comment]
For now, copying the URL of a tweet or a user's profile should be sufficient for any sharing purposes (no matter if you want to share anything in an Android or SFOS application. Please be patient, 0.5 will come soon(tm).
I haven't taken a detailed look into built-in sharing capabilities which are available for reuse by applications yet. However, as I haven't seen anything in the docs, I assume that something like that (e.g. as you have it in the Gallery app) is not available to apps which should go through Harbour...
