### ISSUE TITLE
[Feature] (hashtag) search without retweets

### ISSUE THREAD

**Issue by schmittlauch** [Wunderfitz/harbour-piepmatz#51]
Often the search is much more useful when retweets are not included in there. This is especially true for event hashtags where you want to know what's happening *now* and not what happened 2 hours ago, but is still propagating through someones followers.

So I'd suggest at least an option to not display retweets in the search. Corebird even made that a default behaviour.

**Comment by Wunderfitz** [comment]
Yeah, good point. However, things need to be filtered on the client. Let's see if that's really an easy one as I would expect. ;)

**Comment by DylanVanAssche** [comment]
I think you,can use https://doc.qt.io/archives/qt-5.6/qsortfilterproxymodel.html

**Comment by Wunderfitz** [comment]
@DylanVanAssche Thanks for the hint, but I probably don't even need that one. I'll test my solution over the day and most certainly you'll see a 1.2.1 tomorrow with it.

**Comment by schmittlauch** [comment]
After looking at the latest update (thanks for the quick reaction) I think there was a misunderstanding:
What I meant was removing *all* retweets from the search (at least optionally) to have a strictly-chronological timeline not disrupted by recent retweets of old-age tweets.

I guess the filter you implemented only filters multiple retweets in a row of the same original tweet? Because I still see RTs of old tweets in my search results.

**Comment by Wunderfitz** [comment]
No, there was no misunderstanding. Your request was to remove all retweets. However, I implemented it slightly differently - for a very simple reason: The search only returns results from the last 7 days. The original tweet could be older than 7 days, so that it wouldn't appear at all though there might have been a retweet within the last 7 days which is therefore in the result list. It would be bad in my opinion to remove valid information from the results just because the original tweet is older than 7 days.

In the end, the search results show a list ordered by the last interaction (creation or retweet) without any duplicates.
