### ISSUE TITLE
[Feature request] adjust font size

### ISSUE THREAD

**Issue by jschultz** [Wunderfitz/harbour-piepmatz#55]
Great software! And nice to see such attention to coding style.

Maybe I'm just getting old but on my Xperia X the fonts are a little hard to read. What about having a font scale setting?

Happy to work on this myself, just putting the question out there first in case it's already in the pipeline, or there are difficulties I'm not in a position to foresee.

**Comment by DylanVanAssche** [comment]
Have you tried to change the font size in the Settings app?

**Comment by jschultz** [comment]
Yeah that works, but it affects every app. I just want to see tweets in a slightly larger font.

**Comment by Wunderfitz** [comment]
It's not yet in the pipeline - just because I thought the system-wide setting is sufficient for that purpose. In general, it's probably not that hard to implement, just a lot of manual work as all usages of Theme.fontSize... need to be adjusted to adhere to the new setting. 

If you want to contribute, I'm really open towards PRs, especially as I'm busy with a new SFOS project right now and don't invest much time on Piepmatz, except if there are some showstopper bugs (which this one most certainly isn't ;)).
